name: Demo Cache Workflow
on:
 workflow_dispatch:
#  push:
#     branches:
#       - main
jobs: 
   demo-job:
     runs-on: ubuntu-latest
     steps:
     - name: Check out code
       uses: actions/checkout@v4
     
     - name: Create a Demo file
       run: echo $(date) > Demofile.txt

     - name: Cache Demofile.txt
       uses: actions/cache@v3
       id: demo-cache-id
       env:
         cache-name: Demo-Cache-File
       with:
         path: Demofile.txt
         key: ${{ hashFiles('cache-dependency.txt') }}

     - name: Print The Demo File
       run: cat Demofile.txt
     - name: Cache Found
            if ${{steps.demo-cache-id.outputs.cache-hit == 'true'}}
       run: echo "Cache Found"
     - name: Cache Not Found
            if ${{steps.demo-cache-id.outputs.cache-hit != 'true'}}
       run: echo "Cache Not Found"