name: Demo Cache Workflow
on:
 push:
    branches:
      - main
jobs: 
   demo-job:
     runs-on: ubuntu-latest
     steps:
     - name: Cache Demofile.txt
       uses: actions/cache@v3
       id: demo-cache-id
       env:
         cache-name: Demo-Cache-File
       with:
        path:
            Demofile.txt
        key: ${{hashFiles('cache-dependency.txt')}}