# Actions workflow 
name: Deployment Workflow
on: push
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Echo Hello World
      run: echo "Hello World"
    - name: Content of Index.html
      run: |
         echo "This is line 1"
         echo "This is Line 2"
         cat index.html
         cat courses.html